<?php

namespace App\Livewire\LegalEntity;

use App\Models\Relations\Party;
use Illuminate\Support\Arr;

class EditLegalEntity extends LegalEntity
{
    public function mount(): void
    {
        parent::mount(); // TODO: Change the autogenerated stub

        $this->getLegalEntityForm();
    }

    /**
     * Retrieves the legal entity form data.
     */
    protected function getLegalEntityForm(): void
    {
        parent::getLegalEntity(); // Call the parent method to retrieve basic legal entity data
        $this->getLicenseForm(); // Get the license form data
        $this->getArchiveForm(); // Get the archive form data
        $this->getOwnerLegalEntity(); // Get the owner's legal entity data
        $this->getAccreditationForm(); // Get the accreditation form data status
    }

    /**
     * Retrieves and sets only specific fields related to the license from the legal entity form.
     */
    protected function getLicenseForm(): void
    {
        $license = $this->legalEntity->licenses()?->first();

        if ($license) {
            $this->legalEntityForm->license = Arr::only($this->convertArrayKeysToCamelCase($license->toArray()),
            [
                'type',
                'licenseNumber',
                'issuedBy',
                'issuedDate',
                'expiryDate',
                'activeFromDate',
                'whatLicensed',
                'orderNo'
            ]);
        }
    }

    /**
     * Retrieves and formats specific fields from the archive form.
     */
    protected function getArchiveForm(): void
    {
        // Extracting only 'date' and 'place' fields from the first element of the archive
        if (!empty($this->legalEntityForm->archive)) {
            // if the legal entity has an archive, the 'archivationShow' property is set to true
            $this->legalEntityForm->archivationShow = true;

            $this->legalEntityForm->archive = Arr::only($this->legalEntityForm->archive[0],
                [
                    'date',
                    'place',
                ]
            );
        }
    }

    /**
     * Get the accreditation status of the legal entity
     * (if the legal entity has an accreditation, the 'accreditationShow' property is set to true)
     *
     * @return void
     */
    protected function getAccreditationForm(): void
    {
        if (!empty($this->legalEntityForm->accreditation)) {
            $this->legalEntityForm->accreditationShow = true;
        }
    }

    protected function getOwnerLegalEntity(): void
    {
        $owner = $this->legalEntity->getOwner();

        if (!$owner->exists()) {
            return;
        }

        $ownerParty = $this->getOwnerParty($owner);

        if (!$ownerParty) {
            return;
        }

        $ownerData = $this->prepareOwnerData($ownerParty);
        $this->legalEntityForm->owner = array_merge($this->legalEntityForm->owner ?? [], $ownerData);
    }

    private function getOwnerParty($owner): ?Party
    {
        $ownerAttributes = $owner->attributesToArray();
        return Party::find($ownerAttributes['partyId'] ?? null);
    }

    private function prepareOwnerData(Party $ownerParty): array
    {
        $ownerData = $ownerParty->toArray() ?? [];

        $ownerData['documents'] = $this->prepareDocumentsData($ownerParty);
        $ownerData['position'] = $ownerParty->position ?? null;

        return $ownerData;
    }

    private function prepareDocumentsData(Party $ownerParty): array
    {
        $documents = $ownerParty->documents->toArray() ?? [];

        if (empty($documents)) {
            return [];
        }

        return $this->convertArrayKeysToCamelCase($documents[0]);
    }

    public function updateLegalEntity(): void
    {
        $this->legalEntityForm->onEditValidate();

        if ($this->getErrorBag()->isNotEmpty()) {
            $this->dispatchBrowserEvent('scroll-to-error');
        }

        $this->signLegalEntity(true);
    }

    public function render()
    {
        return view('livewire.legal-entity.edit-legal-entity', ['isEdit' => true]);
    }
}
